dist: trusty

before_install:
  - set -e
  - rustup self update
  - "if [ ${TRAVIS_OS_NAME} == 'osx' ]; then brew upgrade python; fi"
  - sudo pip3 install Django
  - sudo pip3 install bottle
  - sudo pip3 install Flask

addons:
    apt:
        packages:
            - python3-dev
            - python3-pip
language: rust
matrix:
  include:

    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-apple-darwin
      os: osx
          # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta

  allow_failures:
    - rust: nightly
script:
  - cargo test --verbose --all -- --test-threads=1
